### ISSUE TITLE
Fails to build for GitHub pages

### ISSUE THREAD

**Issue by johnsca** [ubuntudesign/jekyll-vanilla-theme#4]
I created a gh-pages branch on my fork of this repo to see what it looks like, and I got an error from GitHub building it.  There error was just "The file `css/main.scss` contains syntax errors" which is not terribly helpful.

**Comment by marcoceppi** [comment]
This is popping up because `css/main.scss` imports `_sass/base.scss` which does this `@import '../node_modules/vanilla-framework/scss/vanilla';`.

Even when including node_modules though, the pages don't render correctly with Github Pages which is the juju.solutions main delivery mechanism.

**Comment by anthonydillon** [comment]
We've updated the project to pull in the `vanilla-framework` dependency as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) instead of [NPM](https://www.npmjs.com/).

Fortunately, Github Pages [pull submodules](https://help.github.com/articles/using-submodules-with-pages/) when they are built, so this should enable anyone to use this with Github Pages without a problem - we have a [demo here](http://ubuntudesign.github.io/jekyll-vanilla-theme/).
